server:
  port: 9873
  
####POM server config###
pom:
  server:
    address: 10.135.9.45
    port: 9970
  cert:
    path: config/wei
    password: changeit
    
## log config ##
logging:
  config: config/logback-spring.xml